# Generated by Django 5.0.1 on 2025-12-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_project_contractors_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='unit_name',
            field=models.CharField(default='Pole', help_text="What are we installing? e.g. 'Pole', 'Gantry', 'Cabinet'", max_length=50),
        ),
    ]
