# Generated by Django 5.0.1 on 2025-12-28 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_projecttype_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'CONTRACTOR'}, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
