# Generated by Django 5.0.1 on 2025-12-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_project_contractors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_file',
            field=models.FileField(blank=True, help_text='Upload a CSV file to populate dropdown options.', null=True, upload_to='project_data/'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='unit_name',
            field=models.CharField(default='Pole', help_text="What are we installing? e.g. 'Pole', 'Gantry'", max_length=50),
        ),
        migrations.CreateModel(
            name='ItemFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The question shown to the contractor', max_length=200)),
                ('field_type', models.CharField(choices=[('TEXT', 'Free Text Question'), ('DROPDOWN', 'Dropdown (from File)')], default='TEXT', max_length=20)),
                ('excel_column', models.CharField(blank=True, help_text='Exact name of the column in the CSV file', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('field_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.itemfielddefinition')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='tracker.pole')),
            ],
        ),
    ]
