# Generated by Django 5.0.1 on 2025-12-30 14:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_project_data_file_alter_projecttype_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_file',
            field=models.FileField(blank=True, help_text='Upload a CSV or Excel file to populate dropdown options.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='project_data/'),
        ),
    ]
