# Generated by Django 5.0.1 on 2025-12-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_project_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfielddefinition',
            name='excel_column',
            field=models.CharField(blank=True, help_text='Column name in the file', max_length=100),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='unit_name',
            field=models.CharField(default='Pole', help_text="e.g. 'Pole', 'Gantry'", max_length=50),
        ),
    ]
