# Generated by Django 5.0.1 on 2025-12-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_itemfielddefinition_excel_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfielddefinition',
            name='is_grouping_key',
            field=models.BooleanField(default=False, help_text='Check this to group items by this field (e.g. Scheme Name)'),
        ),
    ]
