# Generated by Django 5.0.1 on 2025-12-30 16:42

import cloudinary_storage.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_itemfielddefinition_is_grouping_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'UP Government' or 'Adani Power'", max_length=200)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemfielddefinition',
            name='excel_column',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemfielddefinition',
            name='is_grouping_key',
            field=models.BooleanField(default=False, help_text="Check this to use as the 'Village' grouping."),
        ),
        migrations.AlterField(
            model_name='itemfielddefinition',
            name='label',
            field=models.CharField(help_text="e.g. 'Scheme Name'", max_length=200),
        ),
        migrations.AlterField(
            model_name='pole',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_file',
            field=models.FileField(blank=True, help_text='Upload CSV/Excel for dropdowns.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='project_data/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text="This is the 'City' name", max_length=200),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='unit_name',
            field=models.CharField(default='Pole', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CONTRACTOR', 'Contractor')], default='CONTRACTOR', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='tracker.client'),
        ),
    ]
