# Generated by Django 5.0.1 on 2026-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_projectissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
